import { Geist, Geist_Mono, Open_Sans,Space_Grotesk } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import { Footer } from "./components/footer";


const space = Space_Grotesk({ subsets: ['latin'], weight: ['400','500','700'] });
const openSans = Open_Sans({
  subsets: ['latin'],
  weight: ['300','400','600','700','800'],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={`${openSans.className} bg-white`}>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
